### ISSUE TITLE
socket api是什么

### ISSUE THREAD

**Issue by sparrowhe** [TheresaQWQ/SuperBot#4]
启动时提示MAIN - WebSocket Api 连接失败，正在重连
config里的socket的port和event不知道怎么填

**Comment by TheresaQWQ** [comment]
![image](https://user-images.githubusercontent.com/22370654/96366979-a3b40400-117d-11eb-9ea2-6d819c0f4a80.png)
可以参考一下这个

**Comment by passby6someone** [comment]
您好，我遇到了类似的问题，请问 config.ts 中的 token 和 host 该如何填写？
因为之前用过Mirai，请问是否是要在服务器上启动类似的框架来接受websocket的通信？

**Comment by sparrowhe** [comment]
大概是的 目前我的项目没在使用这个机器人 也没深入研究------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;emmm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月10日(星期天) 晚上8:41
收件人:&nbsp;&quot;SakuraBot-dev/SuperBot&quot;<SuperBot@noreply.github.com&gt;;
抄送:&nbsp;&quot;SparrowHe&quot;<1441373096@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SakuraBot-dev/SuperBot] socket api是什么 (#4)

**Comment by fkx4-p** [comment]
> 您好，我遇到了类似的问题，请问 config.ts 中的 token 和 host 该如何填写？
> 因为之前用过Mirai，请问是否是要在服务器上启动类似的框架来接受websocket的通信？

现在框架普遍遵循onebot协议。token对应你任意bot的token，而host对应主机IP(如本地则为127.0.0.1)。

**Comment by passby6someone** [comment]
> > 您好，我遇到了类似的问题，请问 config.ts 中的 token 和 host 该如何填写？
> > 因为之前用过Mirai，请问是否是要在服务器上启动类似的框架来接受websocket的通信？
> 
> 现在框架普遍遵循onebot协议。token对应你任意bot的token，而host对应主机IP(如本地则为127.0.0.1)。

好的，感谢您的回复
